name: minimo
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - maturin=1.7.8
  - ncurses=6.5
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.10.16
  - readline=8.2
  - setuptools=75.8.0
  - tk=8.6.13
  - tomli=2.0.1
  - tzdata=2025a
  - wheel=0.45.1
  - pip:
      - attrs==25.1.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - filelock==3.17.0
      - fsspec==2025.2.0
      - idna==3.10
      - jinja2==3.1.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.26.4
      - packaging==24.2
      - platformdirs==4.3.6
      - protobuf==5.29.3
      - psutil==6.1.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - rpds-py==0.22.3
      - six==1.17.0
      - sympy==1.13.1
      - torch==2.2.2
      - wcwidth==0.2.13
