name: nat-mul
premises: ['eq_symm', 'eq_refl', 'rewrite', 'nat_ind', '+_z', '+_s', 'and_i', 'and_el', 'and_er', 'or_il', 'or_ir', 'or_e', 'not_i', 'not_e',
           'exfalso', 'iff_i', 'iff_el', 'iff_er', 'em']